### PR TITLE
log through serialization

### LINKED ISSUE #946: Exception serializing envelope with `WriteDynamicValue`
No repro yet:

```
Exception:
System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_DeclaringMethod()
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue& value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at Sentry.JsonSerializableExtensions.WriteDynamicValue(Utf8JsonWriter writer, Object value) in /_/src/Sentry/IJsonSerializable.cs:line 106
   at Sentry.SentryEvent.WriteTo(Utf8JsonWriter writer) in /_/src/Sentry/SentryEvent.cs:line 344
   at Sentry.Protocol.Envelopes.JsonSerializable.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/JsonSerializable.cs:line 27
   at Sentry.Protocol.Envelopes.JsonSerializable.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/JsonSerializable.cs:line 28
   at Sentry.Protocol.Envelopes.EnvelopeItem.BufferPayloadAsync(CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/EnvelopeItem.cs:line 64
   at Sentry.Protocol.Envelopes.EnvelopeItem.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/EnvelopeItem.cs:line 101
   at Sentry.Protocol.Envelopes.Envelope.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/Envelope.cs:line 66
   at Sentry.Internal.Http.EnvelopeHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context) in /_/src/Sentry/Internal/Http/EnvelopeHttpContent.cs:line 16
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at Sentry.Internal.Http.GzipBufferedRequestBodyHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/GzipBufferedRequestBodyHandler.cs:line 58
   at Sentry.Internal.Http.RetryAfterHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/RetryAfterHandler.cs:line 64
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/HttpTransport.cs:line 113
   at Sentry.Internal.BackgroundWorker.WorkerAsync() in /_/src/Sentry/Internal/BackgroundWorker.cs:line 134
```

### PR DESCRIPTION
**Pull request by bruno-garcia**
Resolves #946

### CODE REVIEW

File: src/Sentry/IJsonSerializable.cs [hunk 1]
```diff
@@ -15,17 +16,17 @@ public interface IJsonSerializable
         /// Note: this method is meant only for internal use and is exposed due to a language limitation.
         /// Avoid relying on this method in user code.
         /// </remarks>
-        void WriteTo(Utf8JsonWriter writer);
+        void WriteTo(Utf8JsonWriter writer, IDiagnosticLogger logger);
```
Comment (bruno-garcia) [inline src/Sentry/IJsonSerializable.cs:19]: Technically a breaking change but note the `remarks` given above.

For that reason I'm not planning to bump a major.

Comment (lucas-zimerman) [reply src/Sentry/IJsonSerializable.cs:19]: That'll break CrontribSentry 😂, glad it's a thing from the past.

File: src/Sentry/Internal/Extensions/JsonExtensions.cs [hunk 2]
```diff
@@ -150,15 +153,16 @@ public static void Deconstruct(this JsonProperty jsonProperty, out string name,
...
             this Utf8JsonWriter writer,
-            IEnumerable<object?>? arr)
+            IEnumerable<object?>? arr,
+            IDiagnosticLogger logger)
         {
             if (arr is not null)
             {
                 writer.WriteStartArray();
 
                 foreach (var i in arr)
```
Comment (lucas-zimerman) [inline src/Sentry/Internal/Extensions/JsonExtensions.cs:163]: I hardly ever see an 'i' on the code.

File: src/Sentry/Internal/Http/HttpTransport.cs [hunk 3]
```diff
@@ -182,12 +182,13 @@ public async Task SendEnvelopeAsync(Envelope envelope, CancellationToken cancell
             CancellationToken cancellationToken)
         {
             // Spare the overhead if level is not enabled
-            if (_options.DiagnosticLogger?.IsEnabled(SentryLevel.Error) is true)
+            if (_options.DiagnosticLogger?.IsEnabled(SentryLevel.Error) is true &&
+                response.Content is { } content)
```
Comment (lucas-zimerman) [inline src/Sentry/Internal/Http/HttpTransport.cs:186]: test SendEnvelopeAsync_ItemRateLimit_DropsItem broke because `Content` was null

File: src/Sentry/Breadcrumb.cs [hunk 4]
```diff
@@ -114,7 +115,7 @@ public sealed class Breadcrumb : IJsonSerializable
         }
 
         /// <inheritdoc />
-        public void WriteTo(Utf8JsonWriter writer)
+        public void WriteTo(Utf8JsonWriter writer, IDiagnosticLogger? logger)
```
Comment (SimonCropp) [inline src/Sentry/Breadcrumb.cs:118]: isnt this a breaking change?

Comment (bruno-garcia) [reply src/Sentry/Breadcrumb.cs:118]: Yes. i left a comment about this at the interface change

File: src/Sentry/GlobalSessionManager.cs [hunk 5]
```diff
@@ -199,7 +199,7 @@ private void PersistSession(SessionUpdate update, DateTimeOffset? pauseTimestamp
                 var filePath = Path.Combine(_persistenceDirectoryPath, PersistedSessionFileName);
 
                 var persistedSessionUpdate = new PersistedSessionUpdate(update, pauseTimestamp);
-                persistedSessionUpdate.WriteToFile(filePath);
+                persistedSessionUpdate.WriteToFile(filePath, _options.DiagnosticLogger!);
```
Comment (bruno-garcia) [inline src/Sentry/GlobalSessionManager.cs:202]: We'll need to remove this `!`. No other way but to make it nullable I believe

File: src/Sentry/Internal/Extensions/JsonExtensions.cs [hunk 6]
```diff
@@ -285,10 +293,21 @@ public static void Deconstruct(this JsonProperty jsonProperty, out string name,
...
+            {
+                writer.WritePropertyName(propertyName);
+                writer.WriteDynamicValue(value, logger);
+            }
+            catch (Exception e)
+            {
+                // The only location in the protocol we allow dynamic objects are Extra and Contexts
+                // In the event of an instance that can't be serialized, we don't want to throw away a whole event
+                // so we'll suppress issues here.
+                logger?.LogError("Failed to serialize object for property {0}", e, propertyName);
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Extensions/JsonExtensions.cs:309]: We could use the same approach @SimonCropp took and if `logger is null) { throw`;

File: src/Sentry/Internal/Http/CachingTransport.cs [hunk 7]
```diff
@@ -291,7 +291,7 @@ await using (envelopeFile.ConfigureAwait(false))
             await using (stream.ConfigureAwait(false))
 #endif
             {
-                await envelope.SerializeAsync(stream, cancellationToken).ConfigureAwait(false);
+                await envelope.SerializeAsync(stream, _options.DiagnosticLogger!, cancellationToken).ConfigureAwait(false);
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Http/CachingTransport.cs:294]: We'll need to remove this `!`. No other way but to make it nullable I believe

File: src/Sentry/Internal/Http/HttpTransport.cs [hunk 8]
```diff
@@ -251,7 +252,7 @@ public async Task SendEnvelopeAsync(Envelope envelope, CancellationToken cancell
                 await using (envelopeFile)
 #endif
                 {
-                    await processedEnvelope.SerializeAsync(envelopeFile, cancellationToken).ConfigureAwait(false);
+                    await processedEnvelope.SerializeAsync(envelopeFile, _options.DiagnosticLogger!, cancellationToken).ConfigureAwait(false);
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Http/HttpTransport.cs:255]: We'll need to remove this `!`. No other way but to make it nullable I believe

File: src/Sentry/Internal/Extensions/JsonExtensions.cs (hunk 6 above)
Comment (lucas-zimerman) [reply src/Sentry/Internal/Extensions/JsonExtensions.cs]: I went with  `catch Exception ex when (logger != null)`

**Comment by lucas-zimerman** [comment]
Ping @bruno-garcia  for review since he's the PR owner :D

**Comment by bruno-garcia** [comment]
Thank you @lucas-zimerman for fixing this PR

File: src/Sentry/Internal/Extensions/JsonExtensions.cs [hunk 9]
```diff
@@ -285,10 +293,21 @@ public static void Deconstruct(this JsonProperty jsonProperty, out string name,
...
+            IDiagnosticLogger? logger)
         {
-            writer.WritePropertyName(propertyName);
-            writer.WriteDynamicValue(value);
+            try
+            {
+                writer.WritePropertyName(propertyName);
+                writer.WriteDynamicValue(value, logger);
+            }
+            catch (Exception e) when (logger != null)
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Extensions/JsonExtensions.cs:304]:
```suggestion
            catch (Exception e) when (logger is not null)
```
