### PR TITLE
App Hang Tracking for iOS is now disabled by default

### LINKED ISSUE #4150: (MAUI) False App Hang on iOS
### Package

Sentry.Maui

### .NET Flavor

Mono

### .NET Version

9.0.4

### OS

iOS

### OS Version

15.8.4

### Development Environment

Visual Studio v17.x

### SDK Version

8.46.0

### Self-Hosted Sentry Version

24.8.0

### Workload Versions

Related to https://github.com/getsentry/team-mobile/issues/186

Calls to clipboard are being marked as app hang on the native code

### UseSentry or SentrySdk.Init call

```
        builder.UseSentry((option) =>
        {
            option.SendDefaultPii = true;
            option.ReportAssembliesMode = ReportAssembliesMode.None;
            option.Dsn = EnvironmentConfig.SentryDsn;
            option.AutoSessionTracking = false;
            option.TracesSampleRate = 1.0;
            option.AddEventProcessor(new SentryEventProcessor());
            option.AddExceptionProcessor(new SentryExceptionProcessor());
            option.AddExceptionFilterForType<InvalidSessionException>();
            option.Environment = EnvironmentConfig.AppEnvironment.ToString();
            option.AttachScreenshot = true;
            option.SetBeforeScreenshotCapture(BeforeScreenshotCapture);
            if (EnvironmentConfig.AppEnvironment == EAppEnvironment.Prod)
            {
                option.MaxBreadcrumbs = 50;
            }
        });

```

### Steps to Reproduce

On an entry field, try to use the clipboard for more than 2 seconds

### Expected Result

Should not show app hang event

### Actual Result

https://sentry.lkp.app.br/share/issue/b445df88db814198a034bcb6eb6bbaa7/

```
  CoreFoundation      0x180cb3994  <redacted>
  CoreFoundation      0x180c8b530  <redacted>
  CoreFoundation      0x180c8b530  <redacted>
  CoreFoundation      0x180c4cd20  <redacted>
  CoreFoundation      0x180c56e48  <redacted>
  Foundation          0x1823404e0  <redacted>
  UIKitCore           0x183590f7c  <redacted>
  UIKitCore           0x1831de5ac  <redacted>
  libobjc.A           0x1984bb7d0  <redacted>
  libobjc.A           0x1984b8858  <redacted>
  libobjc.A           0x1984c17d4  <redacted>
  UIKitCore           0x1834800f8  <redacted>
  libobjc.A           0x1984bb7d0  <redacted>
  libobjc.A           0x1984b8858  <redacted>
  libobjc.A           0x1984c17d4  <redacted>
  UIKitCore           0x1832235d8  <redacted>
  UIKitCore           0x183123584  <redacted>
  UIKitCore           0x183239278  <redacted>
  App         0x102d2f56c  xamarin_invoke_objc_method_implementation (trampolines.m:649)
  App         0x102f7c534  -[Microsoft_Maui_Platform_MauiTextField release] (registrar.mm:11645)
  App         0x102d2ca90  xamarin_release_managed_ref (runtime.m:1833)
  App         0x102d08c28  interp_to_native_trampoline
  App         0x102f2b374  ves_pinvoke_method (interp.c:1811)
  App         0x102f1e718  mono_interp_exec_method (interp.c:4287)
  App         0x102f1b91c  interp_entry_from_trampoline (interp.c:3228)
  App         0x102d08cfc  native_to_interp_trampoline
  App         0x102f94b90  +[__NSObject_Disposer drain:] (registrar.mm:22474)
  Foundation          0x182353660  <redacted>
  CoreFoundation      0x180cb8448  <redacted>
  CoreFoundation      0x180cc8578  <redacted>
  CoreFoundation      0x180c0a734  <redacted>
  CoreFoundation      0x180c0fe08  <redacted>
  CoreFoundation      0x180c23174  <redacted>
  GraphicsServices    0x1a1766988  <redacted>
  UIKitCore           0x183425a88  <redacted>
  UIKitCore           0x1831bef78  <redacted>
  App         0x102d21284  xamarin_UIApplicationMain (bindings.m:126)
  App         0x102f2ca18  do_icall (interp.c:2426)
  App         0x102f2afec  do_icall_wrapper (interp.c:2466)
  App         0x102f1e564  mono_interp_exec_method (interp.c)
  App         0x102f1c120  interp_runtime_invoke (interp.c:2219)
  App         0x102ee0b48  mono_jit_runtime_invoke (mini-runtime.c:3685)
  App         0x102e7ced8  do_runtime_invoke (object.c:2572)
  App         0x102e7ced8  mono_runtime_invoke_checked (object.c:2788)
  App         0x102e840b8  do_exec_main_checked (object.c)
  App         0x102e840b8  mono_runtime_exec_main_checked (object.c:4808)
  App         0x102ee854c  mono_jit_exec_internal (driver.c:1366)
  App         0x102ee854c  mono_jit_exec (driver.c:1311)
  App         0x102d353b4  xamarin_main (monotouch-main.m:456)
  App         0x102f5d24c  main (main.arm64.mm:79)
```

### PR DESCRIPTION
**Pull request by jamescrosswell**
Resolves #4150:
- https://github.com/getsentry/sentry-dotnet/issues/4150#issuecomment-3025873457

### CODE REVIEW

File: src/Sentry/Platforms/Cocoa/SentryOptions.cs [hunk 1]
```diff
@@ -61,12 +61,12 @@ internal NativeOptions(SentryOptions options)
...
         /// When enabled, the SDK tracks when the application stops responding for a specific amount of
         /// time defined by the <see cref="AppHangTimeoutInterval"/> option.
-        /// The default value is <c>true</c> (enabled).
+        /// The default value is <c>false</c> (disabled).
         /// </summary>
         /// <remarks>
         /// See https://docs.sentry.io/platforms/apple/configuration/app-hangs/
         /// </remarks>
-        public bool EnableAppHangTracking { get; set; } = true;
+        public bool EnableAppHangTracking { get; set; } = false;
```
Comment (Flash0ver) [inline src/Sentry/Platforms/Cocoa/SentryOptions.cs:69]: thought: behavioral breaking change

I'm a bit uncertain about this behavioral breaking change.
Well ... on the one hand, if the feature - per default - is mostly reporting false positives with common usage scenarios, it seems fine.

On the other hand, we would enable it again after #3601 and updating to `sentry-cocoa [8.50.0,)`.
Well ... in that case I suppose we would enable `EnableAppHangTrackingV2` per default.
Or would we remove `EnableAppHangTrackingV2` and have `EnableAppHangTracking` use `sentry-cocoa`'s `enableAppHangTrackingV2` under the hood?
So would switching - eventually - from _AppHangTracking-v1_ to _AppHangTracking-v2_ likewise be a behavioral breaking change? 

Anyway ... I wanted to voice and discuss this thought about potentially switching and confusing defaults between upcoming releases.

Comment (jamescrosswell) [reply src/Sentry/Platforms/Cocoa/SentryOptions.cs:69]: I think this change is more for new users... the defaults enable a feature that's not reliable, which I think is a bug. 

If so,  then we should definitely change the default. It's really just a question of how to communicate this to existing users... and for that, I've done the best I can in the change log. 

I can't think of anything else we can do.

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,10 @@
 
 ## Unreleased
 
+### API changes
+
+- App Hang Tracking for iOS is now disabled by default. You'll need to enable this manually if you want to use it in your applications. ([#4320](https://github.com/getsentry/sentry-dotnet/pull/4320))
```
Comment (bruno-garcia) [inline CHANGELOG.md]: I imagine there's a reason for this. Would be nice to include it here or link to it

**Review by bruno-garcia — APPROVED** [review]
Other than changelog having to be more clear about why we're doing this, makes sense to me. 

If we add v2 by default later we can do it on a major. But remember we can add it to all the on-boarding code snippets first with a comment "give feedback"

File: CHANGELOG.md (hunk 2 above)
Comment (jamescrosswell) [inline CHANGELOG.md]:
```suggestion
- App Hang Tracking for iOS is now disabled by default, until this functionality is more stable. If you want to use it in your applications then you'll need to enable this manually. ([#4320](https://github.com/getsentry/sentry-dotnet/pull/4320))
```

Comment (jamescrosswell) [reply CHANGELOG.md]: Updated the change log to explain the reason for the change.
