### PR TITLE
Fix caching transaction serialization

### LINKED ISSUE #684: Crash: App Crash file Already exists on Cache
Please mark the type framework used:

- [x] ASP.NET MVC
- [x] ASP.NET Web API (OWIN)
- [x] ASP.NET Core
- [x] WPF
- [x] WinForms
- [x] Xamarin
- [x] Other:

Please mark the type of the runtime used:

- [x] .NET Framework
- [x] Mono
- [x] .NET Core

* Version:

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:

```
System.IO.IOException: Cannot create a file when that file already exists
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Sentry.Internal.Http.CachingTransport..ctor(ITransport innerTransport, SentryOptions options)
   at Sentry.Internal.SdkComposer.CreateTransport()
   at Sentry.Internal.SdkComposer.CreateBackgroundWorker()
   at Sentry.SentryClient..ctor(SentryOptions options, IBackgroundWorke
```

```
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Sentry.Internal.Http.CachingTransport..ctor(ITransport innerTransport, SentryOptions options) in C:\PATH
\SentrySdk\OfficialNet\src\Sentry\Internal\Http\CachingTransport.cs:line 68
   at Sentry.Internal.SdkComposer.CreateTransport() in C:\PATH\SentrySdk\OfficialNet\src\Sentry\Internal\SdkComposer.cs:line 40
   at Sentry.Internal.SdkComposer.CreateBackgroundWorker() in C:\PATH\SentrySdk\OfficialNet\src\Sentry\Internal\SdkComposer.cs:line 85
   at Sentry.SentryClient..ctor(SentryOptions options, IBackgroundWorker worker) in C:\PATH\SentrySdk\OfficialNet\src\Sentry\SentryClient.cs:line 57
   at Sentry.SentryClient..ctor(SentryOptions options) in C:\PATH\SentrySdk\OfficialNet\src\Sentry\SentryClient.cs:line 44
   at Sentry.Internal.Hub..ctor(SentryOptions options) in C:\PATH\OfficialNet\src\Sentry\Internal\Hub.cs:line 44
   at Sentry.SentrySdk.Init(SentryOptions options) in C:\PATH\OfficialNet\src\Sentry\SentrySdk.cs:line 92
   at Sentry.SentrySdk.Init(Action`1 configureOptions) in C:\PATH\SentrySdk\OfficialNet\src\Sentry\SentrySdk.cs:line 60
   at Sample.Xamarin.Core.Helpers.SentryInitializer.Init(Boolean enableCache) in C:\PATH\Samples\Sample.Xamarin.Core\Helpers\SentryInitializer.cs:line 13
   at Sample.Xamarin.uwp.App.OnLaunched(LaunchActivatedEventArgs e) in C:\PATH\Samples\Sample.Xamarin.UWP\App.xaml.cs:line 16
```

Init used:
```csharp
            var path = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) ;
            SentrySdk.Init(o =>
            {
                o.InitCacheFlushTimeout = TimeSpan.FromSeconds(1);
                o.CacheDirectoryPath = path;
                o.Debug = true;
                o.Dsn = "https://5a193123a9b841bc8d8e42531e7242a1@o447951.ingest.sentry.io/5560112";
                o.AddIntegration(new SentryXamarinFormsIntegration());
            });
```

I'm linking the Envelopes that I had prior to and during the crash:
[1608840496_aba60a2c8e91459385556077c5984f57_56140151.zip](https://github.com/getsentry/sentry-dotnet/files/5740476/1608840496_aba60a2c8e91459385556077c5984f57_56140151.zip)

https://github.com/getsentry/sentry-dotnet/blob/b2f6b818e09ee107b41377bffd763922e314ecd3/src/Sentry/Internal/Http/CachingTransport.cs#L68-L71

The crash happens because the file on _processing already exists on ../_processing folder.

### LINKED ISSUE #812: Transaction envelope files look broken
### Environment

How do you use Sentry?
Sentry on-premise (21.1.0.dev0)

Which SDK and version?
.NET 3.0.5
Xamarin.Forms 1.0.1
Sentry.Protocol v2.2.0-alpha

### Steps to Reproduce

```
ITransaction transaction = SentrySdk.StartTransaction("name", "operation");
transaction.Finish();
```

### Expected Result

Transaction should have been sent to the Sentry Web.

### Actual Result

Transaction gets rejected.
envelope file looks invalid.

The envelop file only contains the eventId.

Log:

Envelope queued up.
New scope pushed.
Disposing scope.
Storing file C:\Users\XXX\AppData\Local\Packages\YYYY\LocalState\Sentry\F5FD1C2C5D957F03AABA443AB31F4354A68702BB\1612907709_cdfc881f6cfa435f9b98be450fd6fd53_51814648.envelope.
Envelope cdfc881f6cfa435f9b98be450fd6fd53 handed off to transport. #1 in queue.
Flushing cached envelopes.
Reading cached envelope: C:\Users\XXX\AppData\Local\Packages\YYYY\LocalState\Sentry\F5FD1C2C5D957F03AABA443AB31F4354A68702BB\__processing\1612907709_cdfc881f6cfa435f9b98be450fd6fd53_51814648.envelope
Configuring the scope.
Sending cached envelope: cdfc881f6cfa435f9b98be450fd6fd53
**Sentry rejected the envelope cdfc881f6cfa435f9b98be450fd6fd53. Status code: BadRequest. Error detail: invalid event envelope. Error causes: unexpected end of file.**
Successfully sent cached envelope: cdfc881f6cfa435f9b98be450fd6fd53

### PR DESCRIPTION
**Pull request by Tyrrrz**
Fixes #684
Fixes #812

### CODE REVIEW

File: src/Sentry/Internal/Http/CachingTransport.cs [hunk 1]
```diff
@@ -187,6 +187,12 @@ private async Task ProcessCacheAsync(CancellationToken cancellationToken = defau
                 }
                 catch (Exception ex) when (IsRetryable(ex))
                 {
+                    _options.DiagnosticLogger?.LogError(
+                        "Failed to send cached envelope: {0}, retrying after a delay.",
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Http/CachingTransport.cs:191]: Do we just retry after a delay? At this time only on restart on next time an event is sent right?
```suggestion
                        "Failed to send cached envelope: {0}. It will be retired later.",
```

**Review by bruno-garcia — APPROVED** [review]

**Comment by lucas-zimerman** [comment]
Github Action is complaining about this:
Error: D:\a\sentry-dotnet\sentry-dotnet\src\Sentry\Internal\Http\CachingTransport.cs(247,18): error CS1501: No overload for method 'Move' takes 3 arguments [D:\a\sentry-dotnet\sentry-dotnet\src\Sentry\Sentry.csproj]
Error: D:\a\sentry-dotnet\sentry-dotnet\src\Sentry\Internal\Http\CachingTransport.cs(247,18): error CS1501: No overload for method 'Move' takes 3 arguments [D:\a\sentry-dotnet\sentry-dotnet\src\Sentry\Sentry.csproj]
Error: D:\a\sentry-dotnet\sentry-dotnet\src\Sentry\Internal\Http\CachingTransport.cs(247,18): error CS1501: No overload for method 'Move' takes 3 arguments [D:\a\sentry-dotnet\sentry-dotnet\src\Sentry\Sentry.csproj]

File: src/Sentry/Internal/Http/CachingTransport.cs (hunk 1 above)
Comment (Tyrrrz) [reply src/Sentry/Internal/Http/CachingTransport.cs:191]: Tried to be consistent with the other one

image

**Review by lucas-zimerman — APPROVED** [review]
It would be nice to have an additional test to validate the breadcrumb serialization on WriteTo at  Transaction.

**Comment by Tyrrrz** [comment]
> It would be nice to have an additional test to validate the breadcrumb serialization on WriteTo at Transaction.

In order to reproduce this in tests, we need to serialize the envelope twice. The bug manifests only on the second time.
I'm not sure if adding tests like `CanSerializeTwice` and then maybe `CanSerializeThreeTimes` etc is a good idea.

File: src/Sentry/Internal/Http/CachingTransport.cs (hunk 1 above)
Comment (bruno-garcia) [reply src/Sentry/Internal/Http/CachingTransport.cs:191]: I don't follow. Maybe the other messages are misleading?

Just poining out that `retrying after a delay` isn't true

File: src/Sentry/Transaction.cs [hunk 2]
```diff
@@ -150,28 +150,28 @@ public IReadOnlyList<string> Fingerprint
...
-        private Lazy<ConcurrentBag<Breadcrumb>> _breadcrumbsLazy = new();
+        private ConcurrentBag<Breadcrumb> _breadcrumbs = new();
 
         /// <inheritdoc />
-        public IReadOnlyCollection<Breadcrumb> Breadcrumbs => _breadcrumbsLazy.Value;
+        public IReadOnlyCollection<Breadcrumb> Breadcrumbs => _breadcrumbs;
 
         // Not readonly because of deserialization
-        private Lazy<ConcurrentDictionary<string, object?>> _extraLazy = new();
+        private ConcurrentDictionary<string, object?> _extra = new();
```
Comment (bruno-garcia) [inline src/Sentry/Transaction.cs:159]: Wouldn't say it's the same as `Lazy` at all:

https://github.com/microsoft/referencesource/blob/master/mscorlib/system/collections/Concurrent/ConcurrentDictionary.cs#L122

**Comment by bruno-garcia** [comment]
> Ultimately, I think the use of Lazy<...> to avoid allocations is questionable

What about writing a benchmark for this?
Reading the code is already good answer to how questionable it is.

https://github.com/microsoft/referencesource/blob/master/mscorlib/system/collections/Concurrent/ConcurrentDictionary.cs#L122

https://github.com/microsoft/referencesource/blob/master/mscorlib/system/collections/Concurrent/ConcurrentDictionary.cs#L279-L295

File: CHANGELOG.md [hunk 3]
```diff
@@ -2,8 +2,9 @@
 
 ## Unreleased
 
-### Changes
+### Fixes
 
+- Fix caching issues (#815) @Tyrrrz
```
Comment (bruno-garcia) [inline CHANGELOG.md:7]: In retrospect, the changelog entries are really not very helpful:

```suggestion
- Fix serialization of transactions when filesystem caching is enabled. (#815) @Tyrrrz
```

The one below? "fix tracing middleware"? What fix? Does it affect me? Should I upgrade?
