### PR TITLE
fix: Regex for Cron Monitors

### LINKED ISSUE #4372: .NET crontab syntax for hour ranges doesn't work
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

9.0.302

### OS

Any (not platform specific)

### OS Version

_No response_

### Development Environment

Visual Studio v17.x

### SDK Version

5.12.0

### Self-Hosted Sentry Version

25.7.0

### Workload Versions

...

### UseSentry or SentrySdk.Init call

...

### Steps to Reproduce

When using API to set the intervar it does not work with hour ranges. But in web-UI it seems to work.
There are two issues in the API:
* It does not allow to enter weekdays e.g. MON, TUE, ... (but as workaround I can replace them before submitting (see unit-test))
* Ranges are not allowed e.g. 8-18/4 (trigger every 4 hours from 8-18)

Here a unit tests that reproduces the issue:

```csharp
public class SentryMonitorOptionsTests
{
    private static readonly Dictionary<string, string> DayMappings = new(StringComparer.OrdinalIgnoreCase)
    {
        { "MON", "1" },
        { "TUE", "2" },
        { "WED", "3" },
        { "THU", "4" },
        { "FRI", "5" },
        { "SAT", "6" },
        { "SUN", "7" }
    };

    [Theory]
    [InlineData("0  0 * * MON-FRI")]
    [InlineData("0  9 * * MON-FRI")]
    [InlineData("0 18 * * MON-FRI")]
    [InlineData("0 8-18/4 * * MON-FRI")] //this test is failing
    [InlineData("30 8-18/4 * * MON-FRI")] //this test is failing
    [InlineData("0 0 * * *")]
    [InlineData("0 0 * * MON-FRI")]
    [InlineData("0 20 * * MON-FRI")]
    public void Test(string trigger)
    {
        string cron = trigger;
        foreach (var mapping in DayMappings)
        {
            cron = cron.Replace(mapping.Key, mapping.Value, StringComparison.OrdinalIgnoreCase);
        }

        var ctor = typeof(SentryMonitorOptions).GetConstructors(BindingFlags.Instance | BindingFlags.NonPublic).First();
        var options = (SentryMonitorOptions)ctor.Invoke(null);

        options.Interval(cron);
    }
}
```

Image

### Expected Result

To be allowed to use ranges and weekdays

### Actual Result

System.ArgumentException
The provided crontab does not match the expected format of '* * * * *' translating to 'minute', 'hour', 'day of the month', 'month', and 'day of the week'.

### PR DESCRIPTION
**Pull request by jamescrosswell**
Resolves #4372
- https://github.com/getsentry/sentry-dotnet/issues/4372

> [!CAUTION]
> The regex is ridiculously complex now... the only practical way to make sure it works is with loads of unit tests.

### CODE REVIEW

File: src/Sentry/SentryMonitorOptions.cs [hunk 1]
```diff
@@ -57,15 +57,17 @@ public partial class SentryMonitorOptions : ISentryJsonSerializable
...
+    // - Weekdays: 0-7 (0 and 7 both represent Sunday) or MON-SUN
+    private const string ValidCrontabPattern = @"^(\*|(\*\/([1-9][0-9]*))|([0-5]?\d)(-[0-5]?\d)?(\/([1-9][0-9]*))?)(,(\*|(\*\/([1-9][0-9]*))|([0-5]?\d)(-[0-5]?\d)?(\/([1-9][0-9]*))?))*(\s+)(\*|(\*\/([1-9][0-9]*))|([01]?\d|2[0-3])(-([01]?\d|2[0-3]))?(\/([1-9][0-9]*))?)((,(\*|(\*\/([1-9][0-9]*))|([01]?\d|2[0-3])(-([01]?\d|2[0-3]))?(\/([1-9][0-9]*))?))*)?(\s+)(\*|(\*\/([1-9][0-9]*))|([1-9]|[12]\d|3[01])(-([1-9]|[12]\d|3[01]))?(\/([1-9][0-9]*))?)((,(\*|(\*\/([1-9][0-9]*))|([1-9]|[12]\d|3[01])(-([1-9]|[12]\d|3[01]))?(\/([1-9][0-9]*))?))*)?(\s+)(\*|(\*\/([1-9][0-9]*))|([1-9]|1[0-2])(-([1-9]|1[0-2]))?(\/([1-9][0-9]*))?)((,(\*|(\*\/([1-9][0-9]*))|([1-9]|1[0-2])(-([1-9]|1[0-2]))?(\/([1-9][0-9]*))?))*)?(\s+)(\*|(\*\/([1-9][0-9]*))|[0-7](-[0-7])?(\/([1-9][0-9]*))?|(MON|TUE|WED|THU|FRI|SAT|SUN)(-(MON|TUE|WED|THU|FRI|SAT|SUN))?(\/([1-9][0-9]*))?)((,(\*|(\*\/([1-9][0-9]*))|[0-7](-[0-7])?(\/([1-9][0-9]*))?|(MON|TUE|WED|THU|FRI|SAT|SUN)(-(MON|TUE|WED|THU|FRI|SAT|SUN))?(\/([1-9][0-9]*))?))*)?$";
```
[the remark this answers is not in the document]
Comment (jamescrosswell) [reply src/Sentry/SentryMonitorOptions.cs]: This should be fixed now.

File: src/Sentry/SentryMonitorOptions.cs [hunk 2]
```diff
@@ -57,15 +57,17 @@ public partial class SentryMonitorOptions : ISentryJsonSerializable
...
+    // - Weekdays: 0-7 (0 and 7 both represent Sunday) or MON-SUN
+    private const string ValidCrontabPattern = @"^(\*(\/([1-9][0-9]*))?|([0-5]?\d)|([0-5]?\d)-([0-5]?\d)(\/([1-9][0-9]*))?)(,(\*(\/([1-9][0-9]*))?|([0-5]?\d)|([0-5]?\d)-([0-5]?\d)(\/([1-9][0-9]*))?))*(\s+)(\*(\/([1-9][0-9]*))?|([01]?\d|2[0-3])|([01]?\d|2[0-3])-([01]?\d|2[0-3])(\/([1-9][0-9]*))?)(,(\*(\/([1-9][0-9]*))?|([01]?\d|2[0-3])|([01]?\d|2[0-3])-([01]?\d|2[0-3])(\/([1-9][0-9]*))?))*(\s+)(\*(\/([1-9][0-9]*))?|([1-9]|[12]\d|3[01])|([1-9]|[12]\d|3[01])-([1-9]|[12]\d|3[01])(\/([1-9][0-9]*))?)(,(\*(\/([1-9][0-9]*))?|([1-9]|[12]\d|3[01])|([1-9]|[12]\d|3[01])-([1-9]|[12]\d|3[01])(\/([1-9][0-9]*))?))*(\s+)(\*(\/([1-9][0-9]*))?|([1-9]|1[0-2])|([1-9]|1[0-2])-([1-9]|1[0-2])(\/([1-9][0-9]*))?)(,(\*(\/([1-9][0-9]*))?|([1-9]|1[0-2])|([1-9]|1[0-2])-([1-9]|1[0-2])(\/([1-9][0-9]*))?))*(\s+)(\*(\/([1-9][0-9]*))?|[0-7]|(MON|TUE|WED|THU|FRI|SAT|SUN)|[0-7]-[0-7](\/([1-9][0-9]*))?|(MON|TUE|WED|THU|FRI|SAT|SUN)-(MON|TUE|WED|THU|FRI|SAT|SUN)(\/([1-9][0-9]*))?)(,(\*(\/([1-9][0-9]*))?|[0-7]|(MON|TUE|WED|THU|FRI|SAT|SUN)|[0-7]-[0-7](\/([1-9][0-9]*))?|(MON|TUE|WED|THU|FRI|SAT|SUN)-(MON|TUE|WED|THU|FRI|SAT|SUN)(\/([1-9][0-9]*))?))*$";
```
Comment (Flash0ver) [inline src/Sentry/SentryMonitorOptions.cs:70]: suggestion (perf): consider adding the option `RegexOptions.ExplicitCapture`, since we only use `IsMatch` and discard the Capture-Groups.

We could also do this in a follow-up PR, adding a Benchmark as well.

File: test/Sentry.Tests/SentryMonitorOptionsTests.cs [hunk 3]
```diff
@@ -53,6 +53,33 @@ day of month   1-31
     [InlineData("0 0 1 1 0")]           // Minimum values
     [InlineData("*/1 * * * *")]         // Step of 1
     [InlineData("* * 31 */2 *")]        // 31st of every other month
+    // Weekday names
+    [InlineData("0 0 * * MON")]
```
Comment (Flash0ver) [inline test/Sentry.Tests/SentryMonitorOptionsTests.cs]: suggestion (docs): for consistency, would you mind adding comments here too?

File: test/Sentry.Tests/SentryMonitorOptionsTests.cs [hunk 4]
```diff
@@ -53,6 +53,33 @@ day of month   1-31
...
+    [InlineData("0 9 * * MON-FRI")]
+    [InlineData("0 18 * * MON-FRI")]
+    [InlineData("0 0 * * MON-FRI")]
+    [InlineData("0 20 * * MON-FRI")]
+    // Step values with ranges 
+    [InlineData("0-30/15 * * * *")]     // Every 15 minutes from 0-30
```
Comment (Flash0ver) [inline test/Sentry.Tests/SentryMonitorOptionsTests.cs:63]: thought: consider adding a case where a valid step is larger than the valid range

**Review by Flash0ver — APPROVED** [review]

File: src/Sentry/SentryMonitorOptions.cs [hunk 5]
```diff
@@ -57,30 +57,32 @@ public partial class SentryMonitorOptions : ISentryJsonSerializable
...
 
     private SentryMonitorScheduleType _type = SentryMonitorScheduleType.None;
     private string? _crontab;
     private int? _interval;
     private SentryMonitorInterval? _unit;
 
 #if NET9_0_OR_GREATER
-    [GeneratedRegex(ValidCrontabPattern, RegexOptions.IgnoreCase)]
+    [GeneratedRegex(ValidCrontabPattern, RegexOptions.IgnoreCase | RegexOptions.ExplicitCapture)]
```
Comment (Flash0ver) [inline src/Sentry/SentryMonitorOptions.cs:78]: issue (low): inconsistent `RegexOptions`

just noticed that
- the JIT-compiled Regex has `RegexOptions.CultureInvariant`
- both Roslyn-generated Regex do not have `RegexOptions.CultureInvariant`

I can imagine that there won't be an issue with crontab strings ... but we should still keep the `RegexOptions` in sync.

File: test/Sentry.Tests/SentryMonitorOptionsTests.cs [hunk 6]
```diff
@@ -19,13 +19,13 @@ day of month   1-31
...
-    [InlineData("0 0 1 1 *")]
-    [InlineData("0 0 1 * 0")]
-    [InlineData("59 23 31 12 7")]
-    [InlineData("0 */2 * * *")]
-    [InlineData("0 8-10 * * *")]
-    [InlineData("0 6,8,9 * * *")]
+    [InlineData("* * * * *")]           // Every minute
+    [InlineData("0 0 1 1 *")]           // At midnight on January 1st
+    [InlineData("0 0 1 * 0")]           // At midnight on the first day of the month if it's Sunday
+    [InlineData("59 23 31 12 7")]       // At 23:59 on December 31st if it's Saturday
```
Comment (Flash0ver) [inline test/Sentry.Tests/SentryMonitorOptionsTests.cs:25]: typo: `Saturday`/`Sunday`

```suggestion
    [InlineData("59 23 31 12 7")]       // At 23:59 on December 31st if it's Sunday
```

I believe both `0` and `7` are `Sunday` ... and `6` would be `Saturday`

File: src/Sentry/SentryMonitorOptions.cs (hunk 5 above)
Comment (Flash0ver) [inline src/Sentry/SentryMonitorOptions.cs]: question: inconsistent `RegexOptions`

just noticed that
- the JIT-compiled Regex has `RegexOptions.CultureInvariant`
- both Roslyn-generated Regex do not have `RegexOptions.CultureInvariant`

Is the `RegexOptions.CultureInvariant` irrelevant for `[GeneratedRegex]`?
Well ... I can imagine there is no impact on our pattern ... but should we keep the `RegexOptions` in sync?

File: test/Sentry.Tests/SentryMonitorOptionsTests.cs (hunk 6 above)
Comment (Flash0ver) [inline test/Sentry.Tests/SentryMonitorOptionsTests.cs]: typo: `Saturday`/`Sunday`

```suggestion
    [InlineData("59 23 31 12 7")]       // At 23:59 on December 31st if it's Sunday
```

I believe both `0` and `7` are `Sunday` ... and `6` would be `Saturday`

File: test/Sentry.Tests/SentryMonitorOptionsTests.cs [hunk 7]
```diff
@@ -53,6 +53,34 @@ day of month   1-31
...
+    [InlineData("0-45/5 * * * *")]      // Every 5 minutes from 0-45
+    [InlineData("* 8-18/2 * * *")]      // Every 2 hours from 8-18
+    [InlineData("* 0-23/6 * * *")]      // Every 6 hours from 0-23
+    [InlineData("* 9-17/1 * * *")]      // Every hour from 9-17
+    [InlineData("* * 1-15/3 * *")]      // Every 3 days from 1-15
+    [InlineData("* * 1-31/7 * *")]      // Every 7 days from 1-31
+    [InlineData("* * 10-20/2 * *")]     // Every 2 days from 10-20
+    [InlineData("* * * 1-6/2 *")]       // Every 2 months from 1-6
+    [InlineData("* * * 1-12/3 *")]      // Every 3 months from 1-12
+    [InlineData("* * * 3-9/1 *")]       // Every month from 3-9
```
Comment (Flash0ver) [inline test/Sentry.Tests/SentryMonitorOptionsTests.cs]:
```suggestion
    [InlineData("* * * 1-6/2 *")]       // Every 2 months from January-June
    [InlineData("* * * 1-12/3 *")]      // Every 3 months from January-December
    [InlineData("* * * 3-9/1 *")]       // Every month from March-September
```
to not mix it up with minutes from above

File: test/Sentry.Tests/SentryMonitorOptionsTests.cs [hunk 8]
```diff
@@ -53,6 +53,34 @@ day of month   1-31
...
+    [InlineData("* * * * 1-5/2")]       // Every 2 weekdays from 1-5 (Mon-Fri)
+    [InlineData("* * * * 0-6/3")]       // Every 3 days of week from 0-6
```
Comment (Flash0ver) [inline test/Sentry.Tests/SentryMonitorOptionsTests.cs]:
```suggestion
    [InlineData("* * * * 0-6/3")]       // Every 3 days of week from 0-6 (Sun-Sat)
```
