### PR TITLE
fix: boot time detection can fail

### LINKED ISSUE #954: Attempted to divide by zero when calling SentrySdk.Init
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
.Net 3.3.2

### Steps to Reproduce

Just call SentrySdk.Init("url")

### Expected Result

No error

### Actual Result

Exception message: Attempted to divide by zero.
Stack trace: at Sentry.Internal.ProcessInfo..ctor(SentryOptions options, Func1 findPreciseStartupTime) at Sentry.SentrySdk.InitHub(SentryOptions options) at Sentry.SentrySdk.Init(Action1 configureOptions)

### PR DESCRIPTION
**Pull request by bruno-garcia**
Resolves #954

### CODE REVIEW

File: src/Sentry/Internal/ProcessInfo.cs [hunk 1]
```diff
@@ -48,9 +48,20 @@ internal Task PreciseAppStartupTask
...
+                BootTime = now.AddTicks(-Stopwatch.GetTimestamp()
+                                        / (Stopwatch.Frequency
+                                           / TimeSpan.TicksPerSecond));
+            }
+            catch (DivideByZeroException e)
+            {
+                // Seems to have failed on a single Windows Server 2012 on .NET Framework 4.8
+                // https://github.com/getsentry/sentry-dotnet/issues/954
+                _options.DiagnosticLogger?.LogError(
+                    "Failed to find BotoTime: GetTimestamp {0}, Frequency {1}, TicksPerSecond: {2}",
```
Comment (bruno-garcia) [inline src/Sentry/Internal/ProcessInfo.cs:62]:
```suggestion
                    "Failed to find BootTime: GetTimestamp {0}, Frequency {1}, TicksPerSecond: {2}",
```
