### PR TITLE
Revert changes to dangerfile.js

### LINKED ISSUE #1004: Danger is broken
Danger doesn't work on external PRs, probably due to the token not being exposed.

image

### PR DESCRIPTION
**Pull request by Tyrrrz**
Revert danger to its original state, but update the comment message.
Hopefully fixes #1004.

#skip-changelog

### CODE REVIEW

File: dangerfile.js [hunk 1]
```diff
@@ -1,76 +1,97 @@
...
+async function containsChangelog(path) {
+  const contents = await danger.github.utils.fileContents(path);
+  return contents.includes(PR_LINK);
+}
 
-- ${prTitleFormatted} ([#${danger.github.pr.number}](${danger.github.pr.html_url}))
-\`\`\`
+async function checkChangelog() {
+  const skipChangelog =
+    danger.github && (danger.github.pr.body + "").includes("#skip-changelog");
```
Comment (lucas-zimerman) [inline dangerfile.js:54]: It would be nice in the future that skip-change log would be more flexible, not being case sensitive and allowing the `_` symbol, so folks can write `#SKIP-CHANGELOG` or `#skip_changelog` but that could be done in another PR
