### PR TITLE
File system persistence for sessions

### LINKED ISSUE #1096: Cache current session information on disk.
Cache current session information on disk. Close open sessions on restart as Abnormal.

The use case is when a crash happens that doesn't go through the UnhandledException integration (i.e: Native crash). Or the device ran out of battery for example.

The next step after this will be to differentiate abnormal from crash (with the help of native SDKs).

If the session is paused, we should mark it as such and the timestamp. If it dies while paused, on restart we can use that timestamp to end the sessions (as Exited). It's possible that there was a native crash on a background thread while the app was on the background but that we would only be able to answer with support of a native SDK.

To support differentiating Abnormal and Crashed (or even Exited when the session was paused) we need native SDK integration.
From the .NET SDK point of view this is just a callback:

```
SentryOptions
Func<booL>? CrashedLastRun
```
[Similar to what we have on `sentry-cocoa`](https://github.com/getsentry/sentry-cocoa/search?q=crashedlastrun).

Use cases:

Without native SDK integration (callback is null):

1. Session starts, a file is written for the session state. App is put on the background. App dies (out of battery).
On restart Sentry will find the file and end that session as Exited.

2. Sentry SDK starts, an open session is found. Close that session as Abnormal.

With native SDK integration (callback is set to something):

1. SDK Init with an open session on disk. Ask native SDK (Through a callback): Did we crash on the last run? of so we close as Crashed otherwise as Abnormal.

Example Unity Android:

```
SentrySdk.Init(o => {
#if ANDROID
o.CrashedLastRun = () => SentryAndroid.didCrashLastRun();
#elif IOS
o.CrashedLastRun = () => SentryCocoa.didCrashLastRun();
#endif
});
```

In other words:

1. When the .NET SDK starts, it checks for open sessions.
2. If `CrashedLastRun` is null it fallback to the best of its knowlege: Abnormal if session was not paused, otherwise Exited.
3. If callback exists, rely on its value to differentiate between a native crash and Abnormal (Out battery? User killed the app?) and Exited (if was put on the background).

### PR DESCRIPTION
**Pull request by Tyrrrz**
Closes #1096

### CODE REVIEW

File: src/Sentry/SentryOptionsExtensions.cs [hunk 1]
```diff
@@ -236,5 +238,25 @@ internal static void SetupLogging(this SentryOptions options)
...
+        {
+            if (string.IsNullOrWhiteSpace(options.CacheDirectoryPath))
+            {
+                return null;
+            }
+
+            return Path.Combine(
+                options.CacheDirectoryPath,
+                "Sentry",
+                options.Dsn?.GetHashString() ?? "no-dsn"
```
Comment (bruno-garcia) [inline src/Sentry/SentryOptionsExtensions.cs:252]: Should we throw here and end the world?

File: src/Sentry/Internal/Hub.cs [hunk 2]
```diff
@@ -177,6 +178,27 @@ public void BindException(Exception exception, ISpan span)
...
+                    }
+                }
+                catch (Exception ex)
+                {
+                    _options.DiagnosticLogger?.LogError(
+                        "Failed to recover persisted session.",
+                        ex
+                    );
+                }
+            }
```
Comment (Tyrrrz) [inline src/Sentry/Internal/Hub.cs:199]: I put the recovery in `StartSession()` to avoid adding a new method to `IHub`. An alternative would be to put it in the constructor though, but I think it's better to avoid I/O in there. Thoughts?

File: src/Sentry/SentryOptionsExtensions.cs (hunk 1 above)
Comment (Tyrrrz) [reply src/Sentry/SentryOptionsExtensions.cs:252]: You mean disable caching when DSN is not provided?

**Comment by Tyrrrz** [comment]
Still missing support for special handling of paused sessions (will have to store additional data in the file) and `DidCrash` handler. But what do you think about the general direction @bruno-garcia?

File: src/Sentry/GlobalSessionManager.cs [hunk 3]
```diff
@@ -161,7 +164,81 @@ public GlobalSessionManager(SentryOptions options)
...
+        private void DeletePersistedSession()
+        {
+            if (string.IsNullOrWhiteSpace(_persistanceDirectoryPath))
+            {
+                return;
+            }
+
+            try
+            {
+                File.Delete(
```
Comment (bruno-garcia) [inline src/Sentry/GlobalSessionManager.cs:205]:
```suggestion
                if (_logger.IsEnabled(Level.Debug))
                {
                    _logger.LogDebug("Deleting: {0}, File.ReadAllText(_..);
                }
                File.Delete(
```

File: src/Sentry/GlobalSessionManager.cs [hunk 4]
```diff
@@ -161,7 +164,81 @@ public GlobalSessionManager(SentryOptions options)
...
+                    ex
+                );
+            }
+        }
+
+        public SessionUpdate? TryRecoverPersistedSession()
+        {
+            if (string.IsNullOrWhiteSpace(_persistanceDirectoryPath))
+            {
+                return null;
```
Comment (bruno-garcia) [inline src/Sentry/GlobalSessionManager.cs:222]:
```suggestion
                _logger.Debug(..);
                return null;
```

File: src/Sentry/GlobalSessionManager.cs [hunk 5]
```diff
@@ -161,7 +164,81 @@ public GlobalSessionManager(SentryOptions options)
...
+            }
+
+            try
+            {
+                var data = File.ReadAllBytes(Path.Combine(_persistanceDirectoryPath, PersistedSessionFileName));
+                var update = SessionUpdate.FromJson(Json.Parse(data));
+
+                // Switch status to abnormal and initial to false
+                // TODO: crashed for paused sessions
```
Comment (bruno-garcia) [inline src/Sentry/GlobalSessionManager.cs:231]:
```suggestion
                // TODO: Exited for paused sessions
                // TODO: Crashed based on the result of a callback
```

File: src/Sentry/IJsonSerializable.cs [hunk 6]
```diff
@@ -16,4 +17,18 @@ public interface IJsonSerializable
         /// </remarks>
         void WriteTo(Utf8JsonWriter writer);
     }
+
+    internal static class JsonSerializableExtensions
+    {
+        public static byte[] WriteToMemory(this IJsonSerializable serializable)
+        {
+            using var buffer = new MemoryStream();
```
Comment (bruno-garcia) [inline src/Sentry/IJsonSerializable.cs:25]: Prefer FileStream through instead of buffering it all here

File: src/Sentry/SentryOptionsExtensions.cs [hunk 7]
```diff
@@ -236,5 +238,25 @@ internal static void SetupLogging(this SentryOptions options)
                 options.DiagnosticLogger = null;
             }
         }
+
+        internal static string? TryGetDsnSpecificCacheDirectoryPath(this SentryOptions options)
+        {
+            if (string.IsNullOrWhiteSpace(options.CacheDirectoryPath))
+            {
+                return null;
```
Comment (bruno-garcia) [inline src/Sentry/SentryOptionsExtensions.cs:246]: Perhaps at the call site but please log out the path it resolved to or if there was no caching at all

**Comment by Tyrrrz** [comment]
@bruno-garcia some significant changes.
I had to change how the pause/resume works so that it's more encapsulated within session manager, which would allow it to take ownership of the file persistence logic. As a result, it now returns multiple updates from `ResumeSession(...)` back to `Hub`. Ugly, but I don't think there are better options since `GlobalSessionManager` does not encapsulate a reference to `ISentryClient` (although that wouldn't be a horrible idea maybe?).
Evaluating race conditions and thread contention is a nightmare now, too many variables. Part of me just wants to wrap everything in locks.
What do you think?

File: src/Sentry/Internal/Json.cs [hunk 8]
```diff
@@ -15,5 +16,12 @@ public static JsonElement Parse(string json)
             using var jsonDocument = JsonDocument.Parse(json);
             return jsonDocument.RootElement.Clone();
         }
+
+        public static JsonElement Load(string filePath)
+        {
+            using var file = File.OpenRead(filePath);
+            using var jsonDocument = JsonDocument.Parse(file);
+            return jsonDocument.RootElement.Clone();
```
[the remark this answers is not in the document]
Comment (Tyrrrz) [reply src/Sentry/Internal/Json.cs:24]: `jsonDocument.RootElement` is a JSON element backed by a streaming/lazy `JsonDocument`. What `Clone()` does is buffer it all in memory so that the original stream can be safely disposed.

File: src/Sentry/GlobalSessionManager.cs [hunk 9]
```diff
@@ -174,7 +183,141 @@ public GlobalSessionManager(SentryOptions options)
...
+
+            if (string.IsNullOrWhiteSpace(_persistenceDirectoryPath))
+            {
+                _options.DiagnosticLogger?.LogDebug("Persistence directory is not set, returning.");
+                return;
+            }
+
+            try
+            {
+                var filePath = Path.Combine(_persistenceDirectoryPath, PersistedSessionFileName);
```
Comment (bruno-garcia) [inline src/Sentry/GlobalSessionManager.cs:242]:
```suggestion
            var filePath = Path.Combine(_persistenceDirectoryPath, PersistedSessionFileName);
            try
            {
```

File: src/Sentry/GlobalSessionManager.cs [hunk 10]
```diff
@@ -174,7 +183,141 @@ public GlobalSessionManager(SentryOptions options)
...
+                _options.DiagnosticLogger?.LogInfo(
+                    "Deleted persisted session file '{0}'.",
+                    filePath
+                );
+            }
+            catch (Exception ex)
+            {
+                _options.DiagnosticLogger?.LogError(
+                    "Failed to delete persisted session from the file system.",
+                    ex
```
Comment (bruno-garcia) [inline src/Sentry/GlobalSessionManager.cs:275]: Given the suggestion above, what about logging the path so we can peek into the filesystem to figure out why:

```suggestion
                _options.DiagnosticLogger?.LogError(
                    "Failed to delete persisted session from the file system: '{0}'",
                    ex,
                    filePath
```

File: src/Sentry/GlobalSessionManager.cs [hunk 11]
```diff
@@ -174,7 +183,141 @@ public GlobalSessionManager(SentryOptions options)
...
+
+            if (string.IsNullOrWhiteSpace(_persistenceDirectoryPath))
+            {
+                _options.DiagnosticLogger?.LogDebug("Persistence directory is not set, returning.");
+                return null;
+            }
+
+            try
+            {
+                var filePath = Path.Combine(_persistenceDirectoryPath, PersistedSessionFileName);
```
Comment (bruno-garcia) [inline src/Sentry/GlobalSessionManager.cs:292]: Same as above we could life the path and use in the exception logging

**Review by bruno-garcia — APPROVED** [review]
Some small suggestions but LGTM
