### PR TITLE
Associate span exceptions with event exceptions

### LINKED ISSUE #738: Connect errors to the transaction (and span if possible) they happened in
Discussed in: https://github.com/getsentry/sentry-java/pull/1156

If an exception bubbles out of the transaction middleware, the error in Sentry should get connected to the transaction.

It was done in Java recently: https://github.com/getsentry/sentry-java/pull/1156

### PR DESCRIPTION
**Pull request by Tyrrrz**
Closes #738

### CODE REVIEW

File: src/Sentry/Transaction.cs [hunk 1]
```diff
@@ -254,8 +257,13 @@ public void Finish()
         {
             EndTimestamp = DateTimeOffset.UtcNow;
 
+            if (Exception is {} exception)
```
Comment (bruno-garcia) [inline src/Sentry/Transaction.cs:260]: This means that if the exception is logged before we finish the transaction, it won't be bound.

Ideally we'd be able to "connect the exception instance to a span" and if CaptureException happens right after that, it would be connected.

```
void method(ISpan tran) {
var child = tran.StartChild(..);
try {
throw null;
}
catch (e) {
child.Finish(e);
// Will know in which exact Span that the exception happened
SentrySdk.CaptureException(e);
// don't rethrow
}
`

File: src/Sentry/Span.cs [hunk 2]
```diff
@@ -87,7 +95,15 @@ public Span(Transaction parentTransaction, SpanId? parentSpanId, string operatio
...
 
         /// <inheritdoc />
-        public void Finish() => EndTimestamp = DateTimeOffset.UtcNow;
+        public void Finish()
+        {
+            EndTimestamp = DateTimeOffset.UtcNow;
+
+            if (Exception is {} exception)
+            {
+                _hub.BindException(exception, this);
```
Comment (bruno-garcia) [inline src/Sentry/Span.cs:104]: What if we have an overload to `Finish` that takes an Exception instead of the Exception property? Or am I missing a use case where just setting the exception without finishing is needed?

**Review by bruno-garcia — COMMENTED** [review]
I wonder if we can find a way without adding `BindException` to `IHub`

File: src/Sentry/Internal/Polyfills.cs [hunk 3]
```diff
@@ -34,6 +35,17 @@ internal static partial class PolyfillExtensions
...
+
+    public static void AddOrUpdate<TKey, TValue>(
+        this ConditionalWeakTable<TKey, TValue> table,
+        TKey key,
+        TValue value)
+        where TKey : class
+        where TValue : class
+    {
+        table.Remove(key);
+        table.Add(key, value);
```
[the remark this answers is not in the document]
Comment (Tyrrrz) [reply src/Sentry/Internal/Polyfills.cs:47]: > should we lock on table and also lock before looking up on Hub?

Not sure I understood the second part. You mean a lock inside the polyfill?

> Can you use just table[key] = value instead?

Nope.

File: src/Sentry/SentrySdk.cs [hunk 4]
```diff
@@ -357,6 +357,16 @@ public static ITransaction StartTransaction(string name, string operation, strin
...
             => _hub.StartTransaction(name, operation, traceHeader);
 
+        /// <summary>
+        /// Binds specified exception the specified span.
+        /// </summary>
+        /// <remarks>
+        /// This method is used internally and is not meant for public use.
+        /// </remarks>
+        [DebuggerStepThrough]
+        public static void BindException(Exception exception, ISpan span)
```
[the remark this answers is not in the document]
Comment (Tyrrrz) [reply src/Sentry/SentrySdk.cs:367]: Well the `Span` and `Transaction` have a reference to `IHub`, not `Hub`.
Can change it to `Hub` but that will have implications in your unit tests.

File: src/Sentry/Transaction.cs (hunk 1 above)
Comment (Tyrrrz) [reply src/Sentry/Transaction.cs:260]: This is how it works in Java btw.
When should it happen then? When `transaciton.Exception` changes?

File: src/Sentry/Span.cs (hunk 2 above)
Comment (Tyrrrz) [reply src/Sentry/Span.cs:104]: We do have that overload, as an extension method.

File: src/Sentry/Internal/Polyfills.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (bruno-garcia) [reply src/Sentry/Internal/Polyfills.cs:47]: > Not sure I understood the second part. You mean a lock inside the polyfill?

And also when reading from it on the other method. It's not a very elegant solution though

File: src/Sentry/Internal/Hub.cs [hunk 5]
```diff
@@ -184,8 +193,19 @@ public SentryId CaptureEvent(SentryEvent evt, Scope? scope = null)
             {
                 var currentScope = ScopeManager.GetCurrent();
                 var actualScope = scope ?? currentScope.Key;
+
+                // Inject trace information from a linked span
+                if (evt.Exception is { } exception &&
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Hub.cs:198]: I notice d we're not taking trace info from the scopeif there's a span kn the scope we can connect events to it through the span bound to the scope (or currently the transaction property). I guess separate PR for that. This is what other sdks do btw so we should have this on the sdk docs as a spec otherwise no connection between errors and transactions

File: CHANGELOG.md [hunk 6]
```diff
@@ -5,6 +5,7 @@
 ### Features
 
 - Add AddSentryTag and AddSentryContext Extensions for exception class (#834) @lucas-zimerman
+- Associate span exceptions with event exceptions (#848) @Tyrrrz
 
 ### Features
```
Comment (bruno-garcia) [inline CHANGELOG.md:11]:
```suggestion
### Features

- Add AddSentryTag and AddSentryContext Extensions for exception class (#834) @lucas-zimerman
- Associate span exceptions with event exceptions (#848) @Tyrrrz
```

File: src/Sentry/Span.cs [hunk 7]
```diff
@@ -73,9 +76,11 @@ public class Span : ISpan, IJsonSerializable
         /// <summary>
         /// Initializes an instance of <see cref="Span"/>.
         /// </summary>
-        public Span(Transaction parentTransaction, SpanId? parentSpanId, string operation)
+        public Span(IHub hub, Transaction parentTransaction, SpanId? parentSpanId, string operation)
```
Comment (bruno-garcia) [inline src/Sentry/Span.cs:79]: Once we go with the SentryTracer approach taken by @brustolin we can drop this requirement of having IHub in Span

File: src/Sentry/Span.cs [hunk 8]
```diff
@@ -155,6 +175,8 @@ public void WriteTo(Utf8JsonWriter writer)
         /// </summary>
         public static Span FromJson(Transaction parentTransaction, JsonElement json)
         {
+            var hub = DisabledHub.Instance;
```
Comment (bruno-garcia) [inline src/Sentry/Span.cs:178]:
```suggestion
            // A Span deserialized is just used as wire-protocol and doesn't need a Hub
            var hub = DisabledHub.Instance;
```

**Review by bruno-garcia — APPROVED** [review]
