### PR TITLE
Always recalculate payload length

### LINKED ISSUE #1956: Envelope rejected when event has an `object` containing a `DateTime` or `DateTimeOffset` with a positive offset from UTC
This is a simplification of #1523

### Steps to Reproduce

```csharp
using var _ = SentrySdk.Init(o =>
{
    o.Dsn = // dsn
    o.Debug = true;
    o.CacheDirectoryPath = cacheDir;
});

var dto = new DateTimeOffset(2020, 1, 1, 0, 0, 0, TimeSpan.FromHours(1));
var evt = new SentryEvent {Message = "test"};
evt.SetExtra("foo", dto);

SentrySdk.CaptureEvent(evt);

Console.Read();
```

### Expected Result

Message should be sent to sentry successfully.

### Actual Result

```
Error: Sentry rejected the envelope 5243bf81806c4ff3ab7751749aced136. Status code: BadRequest. Error detail: invalid event envelope. Error causes: missing newline after header or payload.
```

This will occur anywhere we expose adding custom information in an `object` type, such as extras, custom context, message template params, etc.  It does not occur when the field in our object model is strongly typed as a `DateTime` or `DateTimeOffset`.  It doesn't occur with other data types (AFAIK).

### PR DESCRIPTION
**Pull request by mattjohnsonpint**
Fixes #1956 and #1523

### CODE REVIEW

File: src/Sentry/Protocol/Envelopes/EnvelopeItem.cs [hunk 1]
```diff
@@ -320,9 +292,13 @@ await foreach (var curByte in stream.ReadAllBytesAsync(cancellationToken).Config
                 prevByte = curByte;
             }
 
-            return
-                Json.Parse(buffer.ToArray(), JsonExtensions.GetDictionaryOrNull)
-                ?? throw new InvalidOperationException("Envelope item header is malformed.");
+            var header = Json.Parse(buffer.ToArray(), JsonExtensions.GetDictionaryOrNull);
```
Comment (bruno-garcia) [inline src/Sentry/Protocol/Envelopes/EnvelopeItem.cs:295]: Is this a refactor or something changed?

File: src/Sentry/Protocol/Envelopes/EnvelopeItem.cs [hunk 2]
```diff
@@ -128,77 +128,49 @@ await using (writer.ConfigureAwait(false))
...
+        public async Task SerializeAsync(Stream stream, IDiagnosticLogger? logger,
+            CancellationToken cancellationToken = default)
         {
-            // Length is known
-            if (TryGetLength() != null)
-            {
-                // Header
-                await SerializeHeaderAsync(stream, logger, cancellationToken).ConfigureAwait(false);
-                await stream.WriteByteAsync((byte)'\n', cancellationToken).ConfigureAwait(false);
+            // Always calculate the length of the payload, as Sentry will reject envelopes that have incorrect lengths
```
Comment (bruno-garcia) [inline src/Sentry/Protocol/Envelopes/EnvelopeItem.cs:135]: If debug mode is enabled should we assert the values we recalculated and the original match and otherwise log? It can help us find discrepancies in round trip serialization

File: src/Sentry/Protocol/Envelopes/EnvelopeItem.cs (hunk 1 above)
Comment (mattjohnsonpint) [reply src/Sentry/Protocol/Envelopes/EnvelopeItem.cs:295]: Artifact between commits.  I'll undo.  Thanks

File: src/Sentry/Protocol/Envelopes/EnvelopeItem.cs (hunk 2 above)
Comment (mattjohnsonpint) [reply src/Sentry/Protocol/Envelopes/EnvelopeItem.cs:135]: No, because it's *valid* for there to be such discrepancies.  That's what this issue is about, essentially.

**Review by SimonCropp — APPROVED** [review]
