### PR TITLE
fix: net8 unknown stack trace methods for JIT methods

### LINKED ISSUE #3924: Profiling - `unknown` stacks on net8
On the current `main` branch, our `Sentry.Samples.Console.Profiling` gets captured with partially missing stack trace information. 

I've debugged EventPipe capture & TraceLog and bisected historical releases and it turns out this is caused by an upgrade to `net8`. 
When I try the sample on v4.13.0 branch it works fine. After changing the target framework in the sample to net8, it breaks and we get these missing stack traces. 
Additionally, I've found out that increasing the `CircularBufferMB` in `StartEventPipeSession` to a higher value helps with the issue on the 4.13 branch, indicating it's caused by the initial rundown being too large so some information is dropped. However, the same "fix" doesn't work on 5.0 or `main` so I'm continuing investigation.

### PR DESCRIPTION
**Pull request by vaind**
Fixes #3924

### CODE REVIEW

File: src/Sentry.Profiling/SampleProfilerSession.cs [hunk 1]
```diff
@@ -22,21 +21,21 @@ private SampleProfilerSession(SentryStopwatch stopwatch, EventPipeSession sessio
...
     internal static EventPipeProvider[] Providers = new[]
     {
-        // Note: all events we need issued by "DotNETRuntime" provider are at "EventLevel.Informational"
-        // see https://learn.microsoft.com/en-us/dotnet/fundamentals/diagnostics/runtime-events
-        // TODO replace Keywords.Default with a subset. Currently it is:
-        //   Default = GC | Type | GCHeapSurvivalAndMovement | Binder | Loader | Jit | NGen | SupressNGen
-        //                | StopEnumeration | Security | AppDomainResourceManagement | Exception | Threading | Contention | Stack | JittedMethodILToNativeMap
-        //                | ThreadTransfer | GCHeapAndTypeNames | Codesymbols | Compilation,
-        new EventPipeProvider(ClrTraceEventParser.ProviderName, EventLevel.Informational, (long) ClrTraceEventParser.Keywords.Default),
+        new EventPipeProvider(ClrTraceEventParser.ProviderName, EventLevel.Verbose, (long) (
```
Comment (vaind) [inline src/Sentry.Profiling/SampleProfilerSession.cs:32]: `EventLevel.Verbose` is the actual fix here. The rest of the change is just an improvement so we don't receive things we don't need.

**Review by jamescrosswell — APPROVED** [review]
👍🏻

**Comment by bruno-garcia** [comment]
This got reverted but it's in the changelog: https://github.com/getsentry/sentry-dotnet/compare/7faf221b6fbf3c293052c30429b38b75564380c4...refs/heads/release/5.1.1

**Comment by vaind** [comment]
> This got reverted but it's in the changelog: [7faf221...refs/heads/release/5.1.1](https://github.com/getsentry/sentry-dotnet/compare/7faf221b6fbf3c293052c30429b38b75564380c4...refs/heads/release/5.1.1)

yeah these changelog items got accidently pulled back in when James was updating the revert PR and pulled changes from main and while I've noticed this yesterday and fixed it  in another PR, I didn't check whether there's already a release triggered.
