### PR TITLE
Fix bug with pre-formatted strings passed to diagnostic loggers

### LINKED ISSUE #2000: Sentry for .net MAUI causes app crash upon startup
### Environment

SaaS (https://sentry.io/)

### Version

_No response_

### Steps to Reproduce

1. Added Sentry to my .net MAUI app - downloaded nuget packages and updated MauiProgram.cs
2. Observed app crash upon startup
3. Removed Sentry and observed that app no longer crashes

### Expected Result

No crash :)

### Actual Result

```
Thread started: <Thread Pool> getsentry/sentry#28
[DOTNET]   Debug: De-queueing event 8901aff4b89e407ca2a6cbb898679f42
[DOTNET]   Debug: Signaling flush completed.
[DOTNET]   Debug: Worker signal triggered: flushing cached envelopes.
[DOTNET]   Debug: Successfully flushed all events up to call to FlushAsync.
[DOTNET]   Debug: Flushing caching transport with remaining flush time.
[DOTNET]   Debug: External FlushAsync invocation: flushing cached envelopes.
[DOTNET]   Debug: No cached file to process.
[DOTNET]   Debug: Reading cached envelope: /data/user/0/com.loungereview.app/cache/sentry/Sentry/EB908074D3CF5F74696DA97F950EB7840CF57699/__processing/1665977574_2595_8901aff4b89e407ca2a6cbb898679f42_-967083357.envelope
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.FormatException: Input string was not in a correct format.
[mono-rt]    at System.Text.ValueStringBuilder.ThrowFormatError()
[mono-rt]    at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
[mono-rt]    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
[mono-rt]    at System.String.Format(String format, Object[] args)
[mono-rt]    at Sentry.Infrastructure.DiagnosticLogger.Log(SentryLevel logLevel, String message, Exception exception, Object[] args) in /_/src/Sentry/Infrastructure/DiagnosticLogger.cs:line 32
[mono-rt]    at Sentry.Android.JavaLogger.Log(SentryLevel level, String message, Object[] args) in /_/src/Sentry/Platforms/Android/JavaLogger.cs:line 12
[mono-rt]    at Sentry.Java.ILoggerInvoker.n_Log_Lio_sentry_SentryLevel_Ljava_lang_String_arrayLjava_lang_Object_(IntPtr jnienv, IntPtr native__this, IntPtr native_p0, IntPtr native_p1, IntPtr native_p2) in /_/src/Sentry/obj/Release/net6.0-android/generated/src/Sentry.Java.ILogger.cs:line 128
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_V(_JniMarshal_PPLLL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 341
[oungereview.ap] createVirtioGpuAddressSpaceStream: create subdevice and get resp
[goldfish-address-space] virtgpu_address_space_create_context_with_subdevice: resp bo: 1 resid 380 mapped 0x714988000000
[oungereview.ap] createVirtioGpuAddressSpaceStream: create subdevice and get resp (done)
[oungereview.ap] createVirtioGpuAddressSpaceStream: ping returned. context ring and buffer sizes 12288 1048576
[oungereview.ap] createVirtioGpuAddressSpaceStream: hostmem id: be, size: 1060864
[oungereview.ap] IOStream flush timeout

```

### PR DESCRIPTION
**Pull request by mattjohnsonpint**
Resolves an issue in the diagnostic loggers caused when .NET's `String.Format` is invoked on a pre-formatted string that contains characters that could be interpreted as formatting characters.   For example, `"{foo:bar}"` passed as a message would raise a `FormatException`.

This was most obvious on Android, when something logged from the native Android SDK that contained arguments was passed upstream to the .NET diagnostic logger.  Accordingly, this PR fixes #2000.

Also with this PR:
- When initializing the Android SDK, don't hook a logger if we aren't logging with `SentryOptions.Debug == true`
- Update `InternalsVisibleTo` to ensure we can use the Sentry Android/Cocoa bindings in our unit tests
- Some refactoring/renaming

The `AndroidDiagnosticLoggerTests` is also the first that is strictly platform-specific, running only with device tests.  The infrastructure of which was created with #2002.

### CODE REVIEW

File: src/Sentry/Platforms/Android/SentrySdk.cs [hunk 1]
```diff
@@ -50,120 +50,130 @@ private static void InitSentryAndroidSdk(SentryOptions options)
         // Make sure we capture managed exceptions from the Android environment
         AndroidEnvironment.UnhandledExceptionRaiser += AndroidEnvironment_UnhandledExceptionRaiser;
 
-        // Now initialize the Android SDK
+        // Define the configuration for the Android SDK
         SentryAndroidOptions? androidOptions = null;
-        SentryAndroid.Init(AppContext, new JavaLogger(options),
-            new OptionsConfigurationCallback(o =>
+        var configuration = new OptionsConfigurationCallback(o =>
```
Comment (mattjohnsonpint) [inline src/Sentry/Platforms/Android/SentrySdk.cs:55]: Note - the only change with this next large block was to extract the `configuration` variable.  Nothing within the block changed.

File: src/Sentry/Platforms/Android/SentrySdk.cs [hunk 2]
```diff
@@ -50,120 +50,130 @@ private static void InitSentryAndroidSdk(SentryOptions options)
...
+        // Now initialize the Android SDK (with a logger only if we're debugging)
+        if (options.Debug && options.DiagnosticLogger is {} logger)
+        {
+            var androidLogger = new AndroidDiagnosticLogger(logger);
+            SentryAndroid.Init(AppContext, androidLogger, configuration);
+        }
+        else
+        {
+            SentryAndroid.Init(AppContext, configuration);
+        }
```
Comment (mattjohnsonpint) [inline src/Sentry/Platforms/Android/SentrySdk.cs:176]: This part changed - we used to always pass in a logger.  Now we only pass one in when debugging.

**Review by SimonCropp — APPROVED** [review]
