### PR TITLE
ref: Handle non json error response messages.

### LINKED ISSUE #688: System.Text.Json.JsonReaderException when Sending large ZIP Attachments
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [x] Xamarin
- [x] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [x] Mono
- [x] .NET Core

* Version:

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:

Console app shows an error on Sentry debug Logger on files larger than 25MB, while on Xamarin Forms, it crashes the app on Android 5.0 while on Android 10 Another error pattern happens, but for now, I think it's better to focus on the Sample below since everyone is able to reproduce i.

Error Stacktrace
```
Error: Error while processing event 7988453045684afa8778d03232cd01e7: System.Text.Json.JsonReaderException: 'R' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at Sentry.Internal.Extensions.HttpClientExtensions.ReadAsJsonAsync(HttpContent content, CancellationToken cancellationToken) in C:\xx\SentrySdk\OfficialNet\src\Sentry\Internal\Extensions\HttpClientExtensions.cs:line 15
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken) in C:\Users\xx\SentrySdk\OfficialNet\src\Sentry\Internal\Http\HttpTransport.cs:line 117
```
Sample code:

```csharp
using Sentry;

static class Program
{
    static void Main()
    {
        SentrySdk.Init( options => {
            options.Dsn = "https://80aed643f81249d4bed3e30687b310ab@o447951.ingest.sentry.io/5428537";
            options.Debug = true;
            });

        System.Console.WriteLine("\n                 26MB File");
        SentrySdk.WithScope((scope) =>
        {
            scope.AddAttachment("../../../lifeforce_by_andromeda_software_development.zip");
            SentrySdk.CaptureMessage("Hello World");
        });
        System.Console.ReadKey();

        System.Console.WriteLine("\n                 2MB File");
        SentrySdk.WithScope((scope) =>
        {
            scope.AddAttachment("../../../2nd_real.zip");
            SentrySdk.CaptureMessage("Hello World");
        });
        System.Console.ReadKey();

        System.Console.WriteLine("\n14MB File");
        SentrySdk.WithScope((scope) =>
        {
            scope.AddAttachment("../../../fr-055_828_final.zip");
            SentrySdk.CaptureMessage("\n                 Hello World");
        });
        System.Console.ReadKey();

        System.Console.WriteLine("\n                 41MB File");
        SentrySdk.WithScope((scope) =>
        {
            scope.AddAttachment("../../../crass-phase_one.zip");
            SentrySdk.CaptureMessage("Hello World");
        });
        System.Console.ReadKey();
    }
}

```

Files used:
26MB https://files.scene.org/view/parties/2007/assembly07/demo/lifeforce_by_andromeda_software_development.zip
2MB https://files.scene.org/view/parties/1993/assembly93/demo/2nd_real.zip
14MB http://www.farbrausch.de/~fg/demos/fr-055_828_final.zip
41MB https://files.scene.org/view/parties/2008/syntax08/demo/crass-phase_one.zip

### LINKED ISSUE #689: HttpTransport debug log don't assume json response
https://github.com/getsentry/sentry-dotnet/blob/14926d5b0279e38fa4989f83b9f207b805a7a32f/src/Sentry/Internal/Http/HttpTransport.cs#L112-L134

Expects json if debug is enabled. It could hit a proxy or something else and not get the expected json response.

It must gracefully handle these cases.

### PR DESCRIPTION
**Pull request by lucas-zimerman**
Closes #689.
Closes #688

### CODE REVIEW

File: src/Sentry/Extensibility/DiagnosticLoggerExtensions.cs [hunk 1]
```diff
@@ -68,17 +68,36 @@ internal static class DiagnosticLoggerExtensions
         public static void LogError<TArg>(
             this IDiagnosticLogger logger,
             string message,
-            Exception exception,
+            Exception? exception,
```
Comment (bruno-garcia) [inline src/Sentry/Extensibility/DiagnosticLoggerExtensions.cs:71]: Not supposed to be nullable.
We should have an overload that doesn't take it then

File: src/Sentry/Internal/Http/HttpTransport.cs [hunk 2]
```diff
@@ -111,25 +111,39 @@ public async Task SendEnvelopeAsync(Envelope envelope, CancellationToken cancell
...
+                        responseJson.GetPropertyOrNull("detail")?.GetString()
+                        ?? DefaultErrorMessage;
+
+                    var errorCauses =
+                        responseJson.GetPropertyOrNull("causes")?.EnumerateArray().Select(j => j.GetString()).ToArray()
+                        ?? Array.Empty<string>();
+
+                    _options.DiagnosticLogger?.LogError(
+                        "Sentry rejected the envelope {0}. Status code: {1}. Error detail: {2}. Error causes: {3}.",
+                        null,
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Http/HttpTransport.cs:128]: Lets have an overload that doesn't take null

**Comment by lucas-zimerman** [comment]
LogError Extensions are going to be implemented on another now, for now, I'm using the old Log pattern.

**Review by bruno-garcia — APPROVED** [review]
