### PR TITLE
Fix issues with envelope deserialization

### LINKED ISSUE #1963: [Xamarin] [iOS & Android] Random Internal Crash in Sentry.Internal.Extensions.StreamExtensions+<ReadAllBytesAsync>
### Package

Sentry

### .NET Flavor

Xamarin

### .NET Version

6.0.401

### OS

Any (not platform specific)

### SDK Version

Sentry Xamarin 1.4.2 / Sentry.NET SDK 3.20.1 

### Self-Hosted Sentry Version

_No response_

### Steps to Reproduce

Unfortunately, we didn't find any repro to the issue.
By seeing the Logs, the app crashes randomly.
On our app, we send many events (for basically every click / navigation)

### Expected Result

The app should not crash.

### Actual Result

```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.CompletionSentinel (System.Object _) [0x00000] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1[TResult].InvokeContinuation () [0x0005a] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1[TResult].SignalCompletion () [0x00063] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1[TResult].SetResult (TResult result) [0x00007] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0

  at Sentry.Internal.Extensions.StreamExtensions+<ReadAllBytesAsync>d__0.MoveNext () [0x001b9] in <c6891296f43443389af454d6ade2ce97>:0

  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine) [0x00000] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00024] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <0e338e4ca0054dd19c56e9a51aa6e2f3>:0
```

### PR DESCRIPTION
**Pull request by mattjohnsonpint**
Improves deserialization by reading the envelope header line in a buffer instead of streaming one character at a time, which should hopefully fix #1963.

Also makes a few other optimizations in nearby code for both serialization and deserialization.

No new tests because we already have a lot of tests that validate it works correctly.

### CODE REVIEW

File: src/Sentry/Protocol/Envelopes/EnvelopeItem.cs [hunk 1]
```diff
@@ -277,23 +268,10 @@ internal static EnvelopeItem FromClientReport(ClientReport report)
             Stream stream,
             CancellationToken cancellationToken = default)
         {
-            var buffer = new List<byte>();
-
-            var prevByte = default(int);
-            await foreach (var curByte in stream.ReadAllBytesAsync(cancellationToken).ConfigureAwait(false))
-            {
-                // Break if found an unescaped newline
-                if (curByte == '\n' && prevByte != '\\')
```
Comment (mattjohnsonpint) [inline src/Sentry/Protocol/Envelopes/EnvelopeItem.cs:286]: Note that the `prevByte` check was extraneous.  An escaped newline is `'\\' + 'n'`, not `'\\' + '\n'`.

File: src/Sentry/Internal/Extensions/StreamExtensions.cs [hunk 2]
```diff
@@ -38,16 +81,15 @@ internal static class StreamExtensions
...
-            using var buffer = new PooledBuffer<byte>(1);
-            buffer.Array[0] = value;
+        // pre-creating this buffer leads to an optimized path when writing
+        private static readonly byte[] NewlineBuffer = {(byte)'\n'};
 
-            await stream.WriteAsync(buffer.Array, 0, 1, cancellationToken).ConfigureAwait(false);
-        }
+        public static async Task WriteNewlineAsync(this Stream stream, CancellationToken cancellationToken = default) =>
+#pragma warning disable CA1835 // the byte-array implementation of WriteAsync is more direct than using ReadOnlyMemory<byte>
+            await stream.WriteAsync(NewlineBuffer, 0, 1, cancellationToken).ConfigureAwait(false);
```
Comment (SimonCropp) [inline src/Sentry/Internal/Extensions/StreamExtensions.cs:89]: why not a direct return?

**Review by SimonCropp — APPROVED** [review]
