### PR TITLE
Fix: braces from tag keys on DefaultSentryScopeStateProcessor.

### LINKED ISSUE #1177: Invalid data (invalid character '{') in path
### Environment

How do you use Sentry?
Sentry SaaS 

Which SDK and version?
.NET 5.0.8, Sentry.AspNetCore 3.8.3

### Steps to Reproduce

Installed Sentry.AspNetCore according to guide:

In Program.cs CreateDefaultBuilder:

```
.ConfigureWebHostDefaults(webBuilder => {
    webBuilder.UseSentry(o => {
        o.Dsn = "https://xxx.ingest.sentry.io/xxx";
        // o.Debug = true;
        o.SendDefaultPii = true;
        o.TracesSampleRate = 0.1;
        o.AddExceptionFilterForType<ApiException>();
});
```

In Startup.cs Configure method:
```
app.UseRouting();
app.UseSentryTracing();
```

### Expected Result

Correct path should show in issue

### Actual Result

image

### PR DESCRIPTION
**Pull request by lucas-zimerman**
This PR removes any brackets from keys applied on `DefaultSentryScopeStateProcessor` if state is `IEnumerable<KeyValuePair<string, object>>`

Close #1177.

### CODE REVIEW

File: src/Sentry/DefaultSentryScopeStateProcessor.cs [hunk 1]
```diff
@@ -11,6 +11,8 @@ namespace Sentry
     /// </summary>
     public class DefaultSentryScopeStateProcessor : ISentryScopeStateProcessor
     {
+        private char[] _trimFilter = new[] { '{', '}' };
```
Comment (SimonCropp) [inline src/Sentry/DefaultSentryScopeStateProcessor.cs:14]: perhaps make it static?

**Review by bruno-garcia — APPROVED** [review]
