### PR TITLE
Fix: Avoid serializing dangerous types.

### LINKED ISSUE #950: System.Text.Json.JsonException when adding complex objects to scope extras
Please mark the type framework used:

Console Application

Please mark the type of the runtime used:

.Net Core 3.1

Please mark the NuGet packages used:

Sentry 3.0.7

When adding a complex object like a TimeZone to a scope extras, the log fails to to be sent to Sentry with the following exception : 
System.Text.Json.JsonException
  HResult=0x80131500
  Message=A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonException_SerializerCycleDetected(Int32 maxDepth)

The exception was caught when debbuging 
at Sentry.JsonSerializableExtensions.WriteDynamicValue
at Sentry.SentryEvent.WiteTo

How should we address this issue? Could unserializable properties be ignored?

Thanks

### LINKED ISSUE #962: Can't add instance of `Exception` to `Extra` or `Contexts`
This was previously possible with `Newtonsoft.Json` but now fails with `System.Text.Json`:

```
using System;
using Sentry;

using (SentrySdk.Init(o =>
{
    o.Debug = true;
    o.Dsn = "...";
}))
{
    try
    {
        throw new Exception("test");
    }
    catch (Exception e)
    {
        SentrySdk.CaptureEvent(new SentryEvent {Contexts = new Contexts() {["ex"] = e}});
    }
}
```

```
   Error: Error while processing event 96a7719b8c6d4a00a2b46f7c93bd0af8: System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues. Path: $.TargetSite.DeclaringType.
 ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues.
   at System.Text.Json.Serialization.Converters.TypeConverter.Write(Utf8JsonWriter writer, Type value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue& value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at Sentry.JsonSerializableExtensions.WriteDynamicValue(Utf8JsonWriter writer, Object value) in /Users/bruno/git/sentry-dotnet/src/Sentry/IJsonSerializable.cs:line 96
   at Sentry.JsonSerializableExtensions.WriteDynamic(Utf8JsonWriter writer, String propertyName, Object value) in /Users/bruno/git/sentry-dotnet/src/Sentry/IJsonSerializable.cs:line 106
   at Sentry.Internal.Extensions.JsonExtensions.WriteDictionaryValue(Utf8JsonWriter writer, IEnumerable`1 dic) in /Users/bruno/git/sentry-dotnet/src/Sentry/Internal/Extensions/JsonExtensions.cs:line 27
   at Sentry.Contexts.WriteTo(Utf8JsonWriter writer) in /Users/bruno/git/sentry-dotnet/src/Sentry/Protocol/Contexts.cs:line 94
   at Sentry.JsonSerializableExtensions.WriteSerializableValue(Utf8JsonWriter writer, IJsonSerializable value) in /Users/bruno/git/sentry-dotnet/src/Sentry/IJsonSerializable.cs:line 30
   at Sentry.JsonSerializableExtensions.WriteSerializable(Utf8JsonWriter writer, String propertyName, IJsonSerializable value) in /Users/bruno/git/sentry-dotnet/src/Sentry/IJsonSerializable.cs:line 39
   at Sentry.SentryEvent.WriteTo(Utf8JsonWriter writer) in /Users/bruno/git/sentry-dotnet/src/Sentry/SentryEvent.cs:line 291
   at Sentry.Protocol.Envelopes.JsonSerializable.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Envelopes/JsonSerializable.cs:line 27
   at Sentry.Protocol.Envelopes.JsonSerializable.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Envelopes/JsonSerializable.cs:line 28
   at Sentry.Protocol.Envelopes.EnvelopeItem.BufferPayloadAsync(CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Envelopes/EnvelopeItem.cs:line 64
   at Sentry.Protocol.Envelopes.EnvelopeItem.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Envelopes/EnvelopeItem.cs:line 101
   at Sentry.Protocol.Envelopes.Envelope.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Envelopes/Envelope.cs:line 66
   at Sentry.Internal.Http.EnvelopeHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context) in /Users/bruno/git/sentry-dotnet/src/Sentry/Internal/Http/EnvelopeHttpContent.cs:line 16
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at Sentry.Internal.Http.GzipBufferedRequestBodyHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Internal/Http/GzipBufferedRequestBodyHandler.cs:line 58
   at Sentry.Internal.Http.RetryAfterHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Internal/Http/RetryAfterHandler.cs:line 64
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Internal/Http/HttpTransport.cs:line 124
   at Sentry.Internal.BackgroundWorker.WorkerAsync() in /Users/bruno/git/sentry-dotnet/src/Sentry/Internal/BackgroundWorker.cs:line 134. #1 in queue.
```

The culprit is on [TargetSite](https://docs.microsoft.com/en-us/dotnet/api/system.exception.targetsite?view=net-5.0#System_Exception_TargetSite) which is of type `MethodBase` and not serializable without persisting some type information which can be exploited.

This limitations is by design. Related issues are [#1](https://github.com/dotnet/runtime/issues/41920), [#2](https://github.com/dotnet/docs/issues/21366), https://github.com/dotnet/runtime/issues/43026

The reasoning from folks from Microsoft:

> We recently published guidance against (de)serializing the DataSet and DataTable types from untrusted input. In keeping with JsonSerializer's emphasis on security, we'll throw a clear NotSupportedException for these types, similar to the behavior for System.Type.

There's a level of regression with this feature gone. Even though it makes sense why the limitation exist.

One work around is to map the `Exception` instance to an anonymous type, for example:

```
try
{
    throw new Exception("test");
}
catch (Exception e)
{
    SentrySdk.CaptureEvent(new SentryEvent {Contexts = new Contexts
    {
        ["ex"] = new
        {
            e.Message,
            e.StackTrace,
            e.Data
        }
    }});
}
```

This successfully serializes the properties `Message`, `StackTrace` and `Data`. More compatible properties could be added in that matter.

Potential improvements:
* Don't drop the whole event if serializing `Extra` or `Context`: We can log the error and continue
* Type check for `Exception` and do the mapping manually for known types. Logging `Warn` for that case would tell the user this is happening and give them a chance to do the mapping upstream for example.
* Add to the documentation (on the migration path, and ideally on a troubleshooting page) Include the work around described above

### LINKED ISSUE #1108: Error Serialization and deserialization of 'System.Type' instances are not supported and should be avoided
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
.NET Core latest 

### Steps to Reproduce

You can try the following project: https://github.com/lucas-zimerman/sample-ef-core-in-asp-net-core
Run and try the first endpoint (or any of them), you'll then notice that on the ide Debug window, there's a Json error related to System.Type

This line is adding the problematic data https://github.com/getsentry/sentry-dotnet/blob/6b60f9cffe1ceb507cbc0d0075afb9ada870603b/src/Sentry/DefaultSentryScopeStateProcessor.cs#L50
where state is Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor and one of the inner parameters is of type System.Type.
image
image
image

### Expected Result

No errors and transactions being registered.

### Actual Result

No transactions were registered due to errors.

### PR DESCRIPTION
**Pull request by lucas-zimerman**
This will stop the drop of events and transactions if their content contains a dangerous class type and junk to be serialized.

## Changes

* Replaced property values by null if the type is
> Exception
> Type
* Replaced property value by null if the namespace belongs to `System.Reflection` (avoiding types that leads to infinite loops by self including themselves).

Close #1108, partially close #962.
EIDT: Might also close #950 because it's one of the type of issues that got fixed by removing references to System.Reflection (I wasn't able to reproduce it with TimeZone)

### CODE REVIEW

File: src/Sentry/Internal/JsonConverters.cs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    {
+        public override bool CanConvert(Type typeToConvert)
+            => typeToConvert?.FullName?.StartsWith("System.Reflection") == true;
+
+        public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
+            => default;
+
+        public override void Write(Utf8JsonWriter writer, T? value, JsonSerializerOptions options)
+            => writer.WriteNullValue();
+    }
```
Comment (Tyrrrz) [inline src/Sentry/Internal/JsonConverters.cs:35]: Sounds like it good be replace by a single class that takes a predicate:

```csharp
internal class JsonConverterScrubber : JsonConverter<object?>
{
    private readonly Func<Type, bool> _canConvert;

    public JsonConverterScrubber(Func<Type, bool> canConvert) =>
    	_canConvert = canConvert;

    public override bool CanConvert(Type typeToConvert) => _canConvert(typeToConvert);

    public override object? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => default;

    public override void Write(Utf8JsonWriter writer, object? value, JsonSerializerOptions options)
        => writer.WriteNullValue();
}
```

File: src/Sentry/Internal/Extensions/JsonExtensions.cs [hunk 2]
```diff
@@ -281,9 +276,9 @@ public static void Deconstruct(this JsonProperty jsonProperty, out string name,
             {
                 writer.WriteStringValue(formattable.ToString(null, CultureInfo.InvariantCulture));
             }
-            else if (value is Type t)
```
Comment (Tyrrrz) [inline src/Sentry/Internal/Extensions/JsonExtensions.cs]: Can we move this entire if/else sequence inside `SentryJsonConverter`?

Comment (lucas-zimerman) [reply src/Sentry/Internal/Extensions/JsonExtensions.cs]: Removed since SentryJsonConverter already did that. Previously it was failing before entering the converter but turned out after the last changes, the problem isn't occurring.

File: test/Sentry.Tests/Internals/JsonTests.cs [hunk 3]
```diff
@@ -0,0 +1,209 @@
...
+                ",\"Object\":{";
+
+            var expectedSerializedException = new[]
+{
+                $"\"Message\":\"{expectedMessage}\"",
+                "\"Data\":{\"" + expectedData.Key + "\":\"" + expectedData.Value + "\"}",
+                "\"InnerException\":null",
+                "\"Source\":\"Sentry.Tests\"",
+                $"\"StackTrace\":{expectedStackTrace}"
+            };
```
Comment (lucas-zimerman) [inline test/Sentry.Tests/Internals/JsonTests.cs:122]:
```suggestion
            var expectedSerializedException = new[]
            {
                $"\"Message\":\"{expectedMessage}\"",
                "\"Data\":{\"" + expectedData.Key + "\":\"" + expectedData.Value + "\"}",
                "\"InnerException\":null",
                "\"Source\":\"Sentry.Tests\"",
                $"\"StackTrace\":{expectedStackTrace}"
            };
```

**Review by bruno-garcia — APPROVED** [review]
