### PR TITLE
fix: flaky tests

### LINKED ISSUE #1386: Flaky `ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested`
The test `ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested` became flaky. First time I see and this test is very old.

Happened on `net461` on Windows (.NET Framework)

https://github.com/getsentry/sentry-dotnet/runs/4508510948?check_suite_focus=true

```
Sentry.Tests.Internals.Http.CachingTransportTests.ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested [FAIL]
Error: Sentry.Tests.Internals.Http.CachingTransportTests.ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested: Assert.False() Failure
  Failed Sentry.Tests.Internals.Http.CachingTransportTests.ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested [131 ms]
  Error Message:
   Assert.False() Failure
Expected: False
Actual:   True
  Stack Trace:
     at Sentry.Tests.Internals.Http.CachingTransportTests.<ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested>d__3.MoveNext() in D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\Internals\Http\CachingTransportTests.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at Sentry.Tests.Internals.Http.CachingTransportTests.<ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested>d__3.MoveNext() in D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\Internals\Http\CachingTransportTests.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Standard Output Messages:
 [Debug]: Storing file D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\bin\Release\net461\5f255f2f-4c92-4ef1-9f71-63abcfa233b2\Sentry\E071FE7F4BE9BFA6EDB6089C375F386F4142AD01\1639411205_-7379_3579c7c3661646718773b1e20d3d6326_6922919.envelope.
     Exception: <none>
Warning: ]: Cache directory is empty.
     Exception: <none>
 [Debug]: Worker signal triggered: flushing cached envelopes.
     Exception: <none>
 [Debug]: Reading cached envelope: D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\bin\Release\net461\5f255f2f-4c92-4ef1-9f71-63abcfa233b2\Sentry\E071FE7F4BE9BFA6EDB6089C375F386F4142AD01\__processing\1639411205_-7379_3579c7c3661646718773b1e20d3d6326_6922919.envelope
     Exception: <none>
 [Debug]: Sending cached envelope: 3579c7c3661646718773b1e20d3d6326
     Exception: <none>
 [Debug]: Canceled sending cached envelope: System.OperationCanceledException: The operation was canceled.
    at NSubstitute.ExceptionExtensions.ExceptionExtensions.<>c__DisplayClass5_0.<ThrowsForAnyArgs>b__0(CallInfo ci)
    at NSubstitute.Core.ReturnValueFromFunc`1.ReturnFor(CallInfo info)
    at NSubstitute.Core.CallResults.TryGetResult(ICall call, Object& result)
    at NSubstitute.Routing.Handlers.ReturnConfiguredResultHandler.Handle(ICall call)
    at NSubstitute.Routing.Route.Handle(ICall call)
    at NSubstitute.Core.CallRouter.Route(ICall call)
    at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at Castle.Proxies.ObjectProxy_17.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken)
    at Sentry.Internal.Http.CachingTransport.<InnerProcessCacheAsync>d__15.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 215
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Sentry.Internal.Http.CachingTransport.<ProcessCacheAsync>d__14.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 162, retrying after a delay.
     Exception: <none>
Error: ]: Exception in background worker of CachingTransport.
     Exception: System.OperationCanceledException: The operation was canceled.
    at NSubstitute.ExceptionExtensions.ExceptionExtensions.<>c__DisplayClass5_0.<ThrowsForAnyArgs>b__0(CallInfo ci)
    at NSubstitute.Core.ReturnValueFromFunc`1.ReturnFor(CallInfo info)
    at NSubstitute.Core.CallResults.TryGetResult(ICall call, Object& result)
    at NSubstitute.Routing.Handlers.ReturnConfiguredResultHandler.Handle(ICall call)
    at NSubstitute.Routing.Route.Handle(ICall call)
    at NSubstitute.Core.CallRouter.Route(ICall call)
    at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at Castle.Proxies.ObjectProxy_17.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken)
    at Sentry.Internal.Http.CachingTransport.<InnerProcessCacheAsync>d__15.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 215
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Sentry.Internal.Http.CachingTransport.<ProcessCacheAsync>d__14.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 172
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Sentry.Internal.Http.CachingTransport.<CachedTransportBackgroundTaskAsync>d__11.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 85
 [Debug]: Background worker of CachingTransport has shutdown.
     Exception: <none>



Failed!  - Failed:     1, Passed:   950, Skipped:     3, Total:   954, Duration: 17 s - Sentry.Tests.dll (net461)
```

### PR DESCRIPTION
**Pull request by bruno-garcia**
Resolves #1386

#skip-changelog

### CODE REVIEW

File: src/Sentry/Internal/Http/CachingTransport.cs [hunk 1]
```diff
@@ -75,35 +75,35 @@ private async Task CachedTransportBackgroundTaskAsync()
                         File.Move(filePath, destinationPath);
                     }
                 }
+            }
+            catch (Exception e)
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Http/CachingTransport.cs:79]: Moved this here since below it would never be reached due to the `catch (Exception)` within the `try` block

File: test/Sentry.Tests/Internals/Http/CachingTransportTests.cs [hunk 2]
```diff
@@ -61,51 +61,75 @@ public async Task ShouldNotLogOperationCanceledExceptionWhenIsCancellationReques
             Debug = true
         };
 
+        var capturingSync = new ManualResetEventSlim();
```
Comment (bruno-garcia) [inline test/Sentry.Tests/Internals/Http/CachingTransportTests.cs:64]: Test was flaky because it relied on stuff happening within `100ms`.

Now the test synchronizes both threads to avoid any Thread.Sleep and flakiness

File: src/Sentry/Internal/Http/CachingTransport.cs [hunk 3]
```diff
@@ -75,35 +75,42 @@ private async Task CachedTransportBackgroundTaskAsync()
...
+            {
+                _options.LogError("Failed to move unprocessed files back to cache.", e);
```
Comment (bruno-garcia) [inline src/Sentry/Internal/Http/CachingTransport.cs:81]: Errors while setting up old files won't stop the worker anymore. It'll log and go through

**Comment by bruno-garcia** [comment]
@SimonCropp please merge if there are no concerns

**Comment by bruno-garcia** [comment]
Argh even the `main` build failed because of this: https://github.com/getsentry/sentry-dotnet/runs/4576503534?check_suite_focus=true

I'll merge and address any feedback on follow up PRs
